proyecto_aion_tailwind/avisosLegales.html, proyecto_aion_tailwind/politicaCookies.html, proyecto_aion_tailwind/politicaPrivacidad.html, proyecto_aion_tailwind/terminosCondiciones.html
Implementación del menú de navegación en todos los HTML
=> Menu nav + estilos

proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/script_tarjetas.js
Mayor distancia de altura entre bloques, adición de detalles que mejoras la experiencia, cambio de algunos textos para mejor comprensión.
=> Precios update

proyecto_aion_tailwind/avisosLegales.html, proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/invertir.html, proyecto_aion_tailwind/politicaCookies.html, proyecto_aion_tailwind/politicaPrivacidad.html, proyecto_aion_tailwind/styles.css, proyecto_aion_tailwind/terminosCondiciones.html
Volver a dar funcionalidad a los menús manteniendo los estilos y eliminando código que estaba repetido
=> Actualizar los menús

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/invertir.html, proyecto_aion_tailwind/styles.css
El margen que daba problemas en el index, invertir y formulario esta corregido
=> Corrección de un margen que daba problemas

proyecto_aion_tailwind/styles.css
He añadido un elemento al css "margin-top: 0" par quitar al final de la web un espacio en blanco que no debería aparecer
=> Actualización de styles.css

proyecto_aion_tailwind/index.html
Ahora las secciones de la web tiene un ancho máximo para para que todo tenga más coherencia
=> Secciones con mayor ancho

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/invertir.html
Paginas de formularios con un ancho máximo para que no se deforme la web al expandir la ventana del navegador
=> Micro cambios

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/mensajeDuda.js, proyecto_aion_tailwind/script_tarjetas.js, proyecto_aion_tailwind/styles.css
ajustados los diseños de tarjetas y varios del index
=> ajustes generales

proyecto_aion_tailwind/avisosLegales.html, proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/invertir.html, proyecto_aion_tailwind/politicaCookies.html, proyecto_aion_tailwind/politicaPrivacidad.html, proyecto_aion_tailwind/terminosCondiciones.html
Se modifican para responsive con movil. formulario se modica campos para que entre mejor en pantalla
=> Modificaciones responsive

proyecto_aion_tailwind/avisosLegales.html, proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/invertir.html, proyecto_aion_tailwind/nav.js, proyecto_aion_tailwind/politicaCookies.html, proyecto_aion_tailwind/politicaPrivacidad.html, proyecto_aion_tailwind/terminosCondiciones.html
Se implementa un archivo nav.js para almacenar la barra de navegador y así optimizamos código
=> cambios-nav

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/mensajeDuda.js
Se modifican las tarjetas de dudas para que sean mucho mas accesibles en version movil aunque aun no estan adaptadas del todo
=> Tarjetas_Dudas

proyecto_aion_tailwind/avisosLegales.html, proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/invertir.html, proyecto_aion_tailwind/politicaCookies.html, proyecto_aion_tailwind/politicaPrivacidad.html, proyecto_aion_tailwind/script_info_tarjetas.js, proyecto_aion_tailwind/terminosCondiciones.html
El menú hamburguesa funciona correctamente.
El botón de la portada en versión móvil esta bien posicionado.
Las tarjetas ahora se muestran correctamente en versión móvil
=> nav+botón+tarjetas arreglado

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/mensajeDuda.js, proyecto_aion_tailwind/styles.css
Se diseñan las tarjetas para que al dar click en ellas muestre el contenido de la tarjeta, aun no esta al 100% ya que al dar click todas las tarjetas se abren a la vez
=> Tarjetas Desplegables

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/mensajeDuda.js, proyecto_aion_tailwind/styles.css
Corregido que se abrieran las 3 tarjetas a la vez, además de retoques estéticos.
=> Tarjetas formulario

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/styles.css
Optimizacion de estilos css, hacer mas vistosas las tarjetas t que el formulario no este pegado a la izquierda del todo
=> Ajustes menores en formulario.html

proyecto_aion_tailwind/footer.js, proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/formularioPrecios.js, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/invertir.html, proyecto_aion_tailwind/nav.js, proyecto_aion_tailwind/script_info_tarjetas.js, proyecto_aion_tailwind/styles.css
Se cambian diseños de hover de botones y modificacion de diseños en entorno moviles
=> Cambios Varios

proyecto_aion_tailwind/formularioPrecios.js
se arregla los precios referenciados en el formulario modal
=> cambios en los precios

proyecto_aion_tailwind/styles.css
Retocar los estilos para que se vea mejor
=> Actualizacion menor de estilos

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/styles.css
La distancia entre el titulo y las tarjetas se ha ampliado y la distancia al footer se ha reducido
=> seccion tarjetas formulario

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/script_tarjetas.js, proyecto_aion_tailwind/script_video.js, proyecto_aion_tailwind/styles.css
=> muchos cambios en el diseño

proyecto_aion_tailwind/nav.js
=> Nav mejora estetica

proyecto_aion_tailwind/menu_hamburguesa.js, proyecto_aion_tailwind/nav.js, proyecto_aion_tailwind/styles.css
ahora el desplegable se queda pegado al nav
=> actualizacion nav

proyecto_aion_tailwind/formulario.html, proyecto_aion_tailwind/mensajeDuda.js, proyecto_aion_tailwind/script_tarjetas.js, proyecto_aion_tailwind/styles.css
se reduce el tamaño y se ajusta a una transicion mas suave, ademas se implementa el cierre de la tarjeta con el click fuera de ella
=> cambios en tarjetas dudas

proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/script_info_tarjetas.js, proyecto_aion_tailwind/styles.css
las imagenes de las tarjetas estan mejor adaptadas y con un pequeño desvanecimiento en la zona superor
=> actualizacion seccion tarjetas

proyecto_aion_tailwind/avisosLegales.html, proyecto_aion_tailwind/index.html, proyecto_aion_tailwind/politicaCookies.html, proyecto_aion_tailwind/politicaPrivacidad.html, proyecto_aion_tailwind/terminosCondiciones.html
modificaciones de cierto detalles para mejorar los estilos vosuales
=> Detalles esteticos
